version: '3.4'

services:

  database:
     image: postgresdb
     restart: always
     ports:
       - 5432:5432
     environment:
         POSTGRES_PASSWORD: damienbod
     build:
       context: PostgresDb/
       dockerfile: Dockerfile    
     volumes:
       - pgdata:/var/lib/postgresql/data
     networks:
       - stocksnetwork 

  stocktickr:
    image: stocktickr
    environment:
      # The PostgreSQL image uses several environment variables which are easy to miss. 
      # While none of the variables are required, they may significantly aid you in using the image.
      # POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_DB, PGDATA
      # see: https://github.com/docker-library/docs/tree/master/postgres
      # values see .env
      #- POSTGRES_USER=test
      - POSTGRES_PASSWORD=damienbod
      #- POSTGRES_DB=test_db
      #- PGDATA=/var/lib/postgresql/data/pgdata      
    ports:
      - "80:8081"
    build:
      context: StockTickRApp/
      dockerfile: Dockerfile
    links:
      - database
    depends_on:
      - "database"  
    networks:
      - stocksnetwork       

volumes:
  pgdata:

networks:
  stocksnetwork:
    driver: bridge

  #csharpclient:
  #  image: csharpclient
  #  ports:
  #    - "5000:5000" 
  #  links:
  #    - "stocktickr:stocktickr"          
  #  build:
  #    context: CsharpClient/
  #    dockerfile: Dockerfile    