version: '3.4'

services:

  database:
     image: postgresdb
     restart: always
     ports:
       - 5432:5432
     # Provide an .env file in the same directory that provides values for the keys:
     # POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_DB   
     env_file:
       - .env  
     build:
       context: PostgresDb/
       dockerfile: Dockerfile    
     volumes:
       - pgdata:/var/lib/postgresql/data
     networks:
       - stocksnetwork 

  stocktickr:
    image: stocktickr
    # The PostgreSQL image uses several environment variables which are easy to miss. 
    # While none of the variables are required, they may significantly aid you in using the image.
    # see: https://github.com/docker-library/docs/tree/master/postgres        
    # Therefore:
    #   Provide an .env file in the same directory that provides values for the keys:
    #   POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_DB  
    env_file:
      - .env
    ports:
      - "80:8081"
    build:
      context: StockTickRApp/
      dockerfile: Dockerfile
    links:
      - database
    depends_on:
      - "database"  
    networks:
      - stocksnetwork       

volumes:
  pgdata:

networks:
  stocksnetwork:
    driver: bridge

  #csharpclient:
  #  image: csharpclient
  #  ports:
  #    - "5000:5000" 
  #  links:
  #    - "stocktickr:stocktickr"          
  #  build:
  #    context: CsharpClient/
  #    dockerfile: Dockerfile    