version: '3.4'

services:
  stocktickr:
    image: stocktickr
    ports:
      - "80:8081"    
    build:
      context: StockTickRApp/
      dockerfile: Dockerfile

  csharpclient:
    image: csharpclient
    ports:
      - "5000:5000"  
    links:
      - "stocktickr:stocktickr"          
    build:
      context: CsharpClient/
      dockerfile: Dockerfile

