version: '3.4'

services:

  database:
    image: microsoft/mssql-server-linux:2017-CU9
    restart: always
    # The mssql-server-linux image requires the following environment flags
    # ACCEPT_EULA=Y
    # SA_PASSWORD=<your_strong_password>
    # MSSQL_PID=<your_product_id | edition_name> (default: Developer)
    # For more information see: https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run     
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    # mounting volumes not working on mac, using data volumes instead. See https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-2017#persist   
    volumes:
      - dbdatavolume:/var/opt/mssql
    networks:
      - stocksnetwork 

  stockprocessor:
    image: stockprocessor
    restart: always
    # The mssql-server-linux image requires the following environment flags:
    # ACCEPT_EULA=Y
    # SA_PASSWORD=<your_strong_password>
    # MSSQL_PID=<your_product_id | edition_name> (default: Developer)
    # For more information see: https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run       
    env_file:
      - .env
    links:
      - database
    depends_on:
      - "database" 
    build:
      context: StockProcessor/
      dockerfile: Dockerfile    
    networks:
      - stocksnetwork 

  stockcollector:
    image: stockcollector
    restart: always
    env_file:
      - .env
    links:
      - stockprocessor
    depends_on:
      - "stockprocessor" 
    build:
      context: StockCollector/
      dockerfile: Dockerfile    
    networks:
      - stocksnetwork    

  stocktickr:
   image: stocktickr
   restart: always
   ports:
     - "80:8081"
   build:
     context: StockTickRApp/
     dockerfile: Dockerfile
   networks:
     - stocksnetwork       

volumes:
  dbdatavolume:

networks:
  stocksnetwork:
    driver: bridge

  #csharpclient:
  #  image: csharpclient
  #  ports:
  #    - "5000:5000" 
  #  links:
  #    - "stocktickr:stocktickr"          
  #  build:
  #    context: CsharpClient/
  #    dockerfile: Dockerfile
  