version: '3.4'

services:

  database:
    image: postgres:11-beta3-alpine
    restart: always
    # The PostgreSQL image uses several environment variables which are easy to miss. 
    # While none of the variables are required, they may significantly aid you in using the image.
    # see: https://github.com/docker-library/docs/tree/master/postgres        
    # Therefore:
    #   Provide an .env file in the same directory that provides values for the keys:
    #   POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_DB  
    # For more information see: https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run     
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stocksnetwork 

  stockdatabase:
    image: stockdatabase
    restart: always
    # The PostgreSQL image uses several environment variables which are easy to miss. 
    # While none of the variables are required, they may significantly aid you in using the image.
    # see: https://github.com/docker-library/docs/tree/master/postgres        
    # Therefore:
    #   Provide an .env file in the same directory that provides values for the keys:
    #   POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_DB  
    # For more information see: https://docs.docker.com/compose/environment-variables/#set-environment-variables-with-docker-compose-run     
    env_file:
      - .env
    links:
      - database
    depends_on:
      - "database" 
    build:
      context: StockDatabase/
      dockerfile: Dockerfile    
    networks:
      - stocksnetwork 

  stockcollector:
    image: stockcollector
    restart: always
    env_file:
      - .env
    links:
      - stockdatabase
    depends_on:
      - "stockdatabase" 
    build:
      context: StockCollector/
      dockerfile: Dockerfile    
    networks:
      - stocksnetwork    

  stocktickr:
   image: stocktickr
   restart: always
   ports:
     - "80:8081"
   build:
     context: StockTickRApp/
     dockerfile: Dockerfile
   networks:
     - stocksnetwork       

volumes:
  pgdata:

networks:
  stocksnetwork:
    driver: bridge

  #csharpclient:
  #  image: csharpclient
  #  ports:
  #    - "5000:5000" 
  #  links:
  #    - "stocktickr:stocktickr"          
  #  build:
  #    context: CsharpClient/
  #    dockerfile: Dockerfile
  