apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o ./deployment/
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: stocktickr
  name: stocktickr
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8081
  selector:
    io.kompose.service: stocktickr
status:
  loadBalancer: {}
