apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o ./deployment/
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: stocktickr
  name: stocktickr
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: stocktickr
    spec:
      containers:
      - image: stocktickr
        name: stocktickr
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
